[env.YoutacRandS-VA]
# Custom name for your testing/dev worker
name = "YoutacRandS-VA-freeway"
workers_dev = true
# Account Id from step 3
account_id = "YOUR_ACCOUNT_ID"
# See step 4.2 to create the R2 Bucket
r2_buckets = [
  { 
    binding = "CARPARK", bucket_name = "carpark-YoutacRandS-VA-52", preview_bucket_name = "carpark-YoutacRandS-VA-preview-52" 
  }
]

[env.YoutacRandS-VA.vars]
DEBUG = "true"
FF_RATE_LIMITER_ENABLED = "false"
CONTENT_CLAIMS_SERVICE_URL = "https://dev.claims.web3.storage"
